[workspace]
resolver = "3"
members = [
    "pluvio_runtime",
    "pluvio_uring",
    "pluvio_ucx", "example/uring_example",
]

exclude = [
    "examples/*",
    "tests/*",
]

[workspace.dependencies]
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter"]}
